### ISSUE TITLE
Works with Vue 3 ?

### ISSUE THREAD

**Issue by NicoJolyAdeo** [d4n5h/Vue-External-Component#4]
Hi, i have the error : [Vue warn]: Invalid VNode type: undefined (undefined)
Something to config for Vue 3 ?
Thank you

**Comment by d4n5h** [comment]
@NicoJolyAdeo Here you go - https://vuejs.org/guide/extras/web-components.html
Sorry for the late response.

**Comment by d4n5h** [comment]
> Hi, i have the error : [Vue warn]: Invalid VNode type: undefined (undefined) Something to config for Vue 3 ? Thank you

Please check out [vue3-external-component](https://www.npmjs.com/package/vue3-external-component)

It works with Vue3 and it doesn't need to convert the component to web component.
